config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index" # tempomary walk around
  resources :jewels  do
    get :autocomplete, on: :collection
  end
  resources :projects
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/jewel.rb
# frozen_string_literal: true
class Jewel < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: :name, using: { tsearch: { prefix: true } }

  has_and_belongs_to_many :projects

  validates :name, presence: true
end

app/models/project.rb
# frozen_string_literal: true
class Project < ApplicationRecord
  has_and_belongs_to_many :jewels

  validates :name, :url, presence: true
  validates :stars_count, presence: { unless: proc { |p| p.new_record? } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :turbo_frame_request_variant
  
  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_action :set_jewel, only: %i[ show edit update destroy ]

  # GET /jewels or /jewels.json
  def index
    @jewels = Jewel.all
  end

  def autocomplete
    @tags = []
    if params[:q].present?
      @tags = Jewel.search_by_name(params[:q])
      @tags = @tags.limit(3).pluck(:name)
    end
    render layout: false
  end

  # GET /jewels/1 or /jewels/1.json
  def show
  end

  # GET /jewels/new
  def new
    @jewel = Jewel.new
  end

  # GET /jewels/1/edit
  def edit
  end

  # POST /jewels or /jewels.json
  def create
    @jewel = Jewel.new(jewel_params)

    respond_to do |format|
      if @jewel.save
        format.html { redirect_to jewel_url(@jewel), notice: "Jewel was successfully created." }
        format.json { render :show, status: :created, location: @jewel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jewels/1 or /jewels/1.json
  def update
    respond_to do |format|
      if @jewel.update(jewel_params)
        format.html { redirect_to jewel_url(@jewel), notice: "Jewel was successfully updated." }
        format.json { render :show, status: :ok, location: @jewel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jewels/1 or /jewels/1.json
  def destroy
    @jewel.destroy

    respond_to do |format|
      format.html { redirect_to jewels_url, notice: "Jewel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewel
      @jewel = Jewel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jewel_params
      params.require(:jewel).permit(:name)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    projects = Project.includes(:jewels).where.not(stars_count: 0).order(stars_count: :desc)
    params.delete(:commit)
    if params[:search].present?
      @selected_jewel = Jewel.where("name LIKE ?", "#{params[:search]}").first
      projects = projects.joins(:jewels).where(jewels: [@selected_jewel.id])
    end
    @pagy, @projects = pagy(projects, items: 20)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :stars_count, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jewels_helper.rb
module JewelsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def ruby_toolbox_url(name)
   "https://www.ruby-toolbox.com/projects/#{name}"
  end
end

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl" data-controller="hello">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/jewels/_form.html.erb
<%= form_with(model: jewel, class: "contents") do |form| %>
  <% if jewel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(jewel.errors.count, "error") %> prohibited this jewel from being saved:</h2>

      <ul>
        <% jewel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/jewels/autocomplete.html.erb
<% @tags.each do |tag| %>
  <li class="list-group-item border px-2 py-1 text-m font-medium" role="option"><%= tag %></li>
<% end %>

app/views/jewels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing jewel</h1>

  <%= render "form", jewel: @jewel %>

  <%= link_to "Show this jewel", @jewel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to jewels", jewels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/jewels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Jewels</h1>
    <%= link_to 'New jewel', new_jewel_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="jewels" class="min-w-full">
    <%= render @jewels %>
  </div>
</div>

app/views/jewels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New jewel</h1>

  <%= render "form", jewel: @jewel %>

  <%= link_to 'Back to jewels', jewels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/jewels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @jewel %>

    <%= link_to 'Edit this jewel', edit_jewel_path(@jewel), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this jewel', jewel_path(@jewel), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to jewels', jewels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aggemregator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stars_count %>
    <%= form.number_field :stars_count, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_pager.html.erb
<div id="pager" class="min-w-full my-8 flex justify-between">
  <div>
    <% if pagy.next %>
      <%= link_to(
        "Load more widgets",
        projects_path(page: pagy.next, search: params[:search]),
        class: "rounded py-3 px-5 bg-gray-600 text-white block hover:bg-gray-800",
        data: {
          turbo_frame: "page_handler",
          turbo_action: "advance",
          controller: "autoclick"
        }
      ) %>
    <% end %>
  </div>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="border-solid border-2">
  <p class="my-5 bt-2">
    <span class="block font-medium mb-1">Name:</span>
    <%= project.name %>
  </p>

  <p class="my-5 bt-2">
    <span class="block font-medium mb-1">Description:</span>
    <%= project.description %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Stars count:</span>
    <%= project.stars_count %>
  </p>

  <p class="my-5">
    <span class="block font-medium mb-1">Url:</span>
    <%= link_to(project.url, project.url, target: "_blank", class: "text-sky-700") %>
  </p>

  <p class="my-5">
    <% project.jewels.each do |jewel| %>
      <span class="font-bold text-sky-700 visited:text-indigo-700 mr-1">
        <%= link_to(jewel.name, projects_path(search: jewel.name))%>
      </span>
    <% end %>
  </p>
  <p class="my-5">
    <%= link_to "Show this project", project %>
  </p>
</div>

app/views/projects/_searchbar.html.erb
  <div class="max-w-xs mx-auto bg-white">
    <%= form_tag(projects_path, method: :get) do %>
      <div data-controller="autocomplete" data-autocomplete-url-value=<%=autocomplete_jewels_path%>>
        <input type="text" class="w-full" data-autocomplete-target="input" value="<%=params[:search]%>" placeholder='Type gem name...'/>
        <input type="hidden" name="search" data-autocomplete-target="hidden">
        <ul class="list-group absolute bg-slate-50 w-80" data-autocomplete-target="results"></ul>
      </div>

      <%= submit_tag("", class: "hidden", disabled: true)%>
    <% end %> 
  </div>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "append",
    target: "projects",
    template: %(#{render @projects}) 
  ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "pager", pagy: @pagy})
    ) %>
<% end %>

app/views/projects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center py-2">
    <h1 class="font-bold text-4xl">Projects <span class="text-sky-700">(<%=@pagy.count%>)</span></h1>
  </div>
  <% if @selected_jewel.present? %>
    <div class="float-right bg-slate-100 p-6 m-1">
      <div>
        selected gem: <%=@selected_jewel.name%>
      </div>
      <%
=begin%>
 <div>
        <%=link_to("github", @selected_jewel.url, target: "_blank", class: "text-sky-700") %>
      </div>
<%
=end%>

      <div>
        <%=link_to("toolbox", ruby_toolbox_url(@selected_jewel.name), target: "_blank", class: "text-sky-700")%>
      </div>
    </div>
  <% end %>

  <%= render "searchbar" %>

  <%= turbo_frame_tag "page_handler" %>

  <div id="projects" class="min-w-full">
    <%= render @projects %>
  </div>

  <%= render "pager", pagy: @pagy %>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @project %>

    <%= link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>